theme: minimal-jekyll-theme

title: Bo Jeanes
url: https://bjeanes.com
logo: https://avatars2.githubusercontent.com/u/2560?s=200&v=4

author: bo

twitter:
  username: "bjeanes"

social:
  links:
    - https://twitter.com/bjeanes
    - https://github.com/bjeanes

permalink: /:title/
date_format: "%-d %b %Y"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  sass_dir: _sass

include:
  - _pages

exclude:
  - bin
  - .buildkite
  - .github
  - index.md
  - Gemfile
  - Gemfile.lock

jekyll-archives:
  layout: "archive"
  enabled:
    - categories
    - tags
    - year
    - month
    - day
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"
